# Generated by Selenium IDE
import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait


class TestAmazon():
    def setup_method(self):
        self.driver = webdriver.Chrome("chromedriver.exe")
        self.driver.implicitly_wait(10)
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def test_amazon(self):
        self.driver.get("https://vendorcentral.amazon.com/")
        self.driver.find_element(By.ID, "login-button-container").click()
        self.driver.find_element(By.ID, "ap_email").click()
        self.driver.find_element(By.ID, "ap_email").send_keys("")
        self.driver.find_element(By.ID, "ap_password").send_keys("")
        self.driver.find_element(By.ID, "signInSubmit").click()
        self.driver.find_element(By.LINK_TEXT, "Customer Reviews").click()
        # element = self.driver.find_element(By.LINK_TEXT, "Demographics")
        # actions = ActionChains(self.driver)
        # actions.move_to_element(element).perform()
        # element = self.driver.find_element(By.CSS_SELECTOR, "body")
        # actions = ActionChains(self.driver)
        # actions.move_to_element(element, 0, 0).perform()
        time.sleep(5)
        self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-reportingRange").click()
        self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-dropdown-item:nth-child(1)").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH, "//*[@id=\"dashboard-filter-applyCancel\"]/div/awsui-button[2]/button").click()
        time.sleep(5)
    # self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-variant-primary").click()


        # element = self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-reviewTrendVisualType strong")
        # actions = ActionChains(self.driver)
        # actions.move_to_element(element).perform()
        # element = self.driver.find_element(By.CSS_SELECTOR, "body")
        # actions = ActionChains(self.driver)
        # actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-visCols").click()
        time.sleep(1)

        # element = self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-visCols")
        # actions = ActionChains(self.driver)
        # actions.move_to_element(element).perform()
        # element = self.driver.find_element(By.CSS_SELECTOR, "body")
        # actions = ActionChains(self.driver)
        # actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-dropdown-item:nth-child(1)").click()

        self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-visCols").click()
        self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-dropdown-item:nth-child(2)").click()

        self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-visCols").click()
        self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-dropdown-item:nth-child(3)").click()

        self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-visCols").click()
        self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-dropdown-item:nth-child(4)").click()

        self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-visCols").click()
        self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-dropdown-item:nth-child(5)").click()

        self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-visCols").click()
        self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-dropdown-item:nth-child(6)").click()

        self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-visCols").click()
        self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-dropdown-item:nth-child(7)").click()

        self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-visCols").click()
        self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-dropdown-item:nth-child(8)").click()

        self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-visCols").click()
        self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-dropdown-item:nth-child(9)").click()

        self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-visCols").click()
        self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-dropdown-item:nth-child(10)").click()

        self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-visCols").click()
        self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-dropdown-item:nth-child(11)").click()

        self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-visCols").click()
        self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-dropdown-item:nth-child(12)").click()

        self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-visCols").click()
        self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-dropdown-item:nth-child(13)").click()

        self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-visCols").click()
        # element = self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-visCols")
        # actions = ActionChains(self.driver)
        # actions.move_to_element(element).perform()
        # element = self.driver.find_element(By.CSS_SELECTOR, "body")
        # actions = ActionChains(self.driver)
        # actions.move_to_element(element, 0, 0).perform()
        # self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-dropdown-item:nth-child(3)").click()
        # element = self.driver.find_element(By.CSS_SELECTOR, "#dashboard-filter-visCols .awsui-button")
        # actions = ActionChains(self.driver)
        # actions.move_to_element(element).perform()

        row = 3
        col = 6

        for r in range(row, 0, -1):
            for c in range(col, 0, -1):
                self.driver.find_element(By.CLASS_NAME, "date-picker-icon").click()
                string = "/html/body/div[4]/div/div[2]/div[2]/div[" + str(r) + "]/div[" + str(c) + "]"
                self.driver.find_element(By.XPATH, string).click()
                time.sleep(1)
                self.driver.find_element(By.XPATH, "//*[@id=\"dashboard-filter-applyCancel\"]/div/awsui-button[2]/button").click()
                time.sleep(2)
                self.driver.find_element(By.CSS_SELECTOR, "#downloadButton .awsui-button").click()
                self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-dropdown-item-has-bottom-border").click()
                wait = WebDriverWait(self.driver, 60).until(expected_conditions.alert_is_present())

                self.driver.switch_to.alert.accept()
                time.sleep(2)

            col = 7


script = TestAmazon()
script.setup_method()
script.test_amazon()
script.teardown_method()
